name: cataclysmdda # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '2023-03-01-0054' # just for humans, typically '1.2+git' or '1.3.2'
summary:  Cataclysm: Dark Days Ahead is a turn-based survival game set in a post-apocalyptic world.
description: |
   Struggle to survive in a harsh, persistent, procedurally generated world. Scavenge the remnants of a dead civilization for food, equipment, or, if you are lucky, a vehicle with a full tank of gas to get you the hell out of Dodge. Fight to defeat or escape from a wide variety of powerful monstrosities, from zombies to giant insects to killer robots and things far stranger and deadlier, and against the others like yourself, that want what you have…

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  cata_icon.png
title: Cataclysm Dark Days Ahead

apps:
  cataclysmdda:
    command: cataclysm-launcher
parts:
  cataclysmdda:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      cataclysmdda: build/
      cataclysmdda.1: man/man1/

architectures:
  - build-on: amd64

